/** FICTIONAL example for /example/constellation. Noor Halvorsen is an invented person.
 * Shaped exactly like a published snapshot, so it exercises the real adapter. */
export const CONSTELLATION_EXAMPLE_SNAPSHOT = {
  at: "2026-09-12T09:00:00.000Z",
  profile: {
    name: "Noor Halvorsen (example)",
    headline: "Lead product designer, Civic Works Lisbon",
    bio: "A designer who plays cello, co-runs a neighbourhood garden, teaches kids to code on Saturdays and has just become a beekeeper. She learns best by making things with other people.",
    template: "playground",
    accent: "#bca4f4",
    socials: [],
    sections: [],
    experience: [
      {
        id: "w1",
        title: "Junior designer",
        org: "Fjordlab",
        start: "2010",
        end: "2013",
        summary:
          "First job out of architecture school, at a small Oslo studio. Wayfinding, exhibition graphics, and learning that most of design is listening.",
        public: true,
      },
      {
        id: "w2",
        title: "Product designer",
        org: "Kelp Health",
        start: "2013",
        end: "2018",
        summary:
          "Designed a medication and appointments app used by clinics across Norway. Moved from screens to services.",
        public: true,
        projects: ["w3"],
      },
      {
        id: "w4",
        title: "Lead designer",
        org: "Civic Works Lisbon",
        start: "2020",
        current: true,
        summary:
          "Leads a team of five designing public services with the city. Mentors juniors and argues for plain language in every meeting.",
        public: true,
        projects: ["w5", "w6"],
      },
      {
        id: "t2",
        title: "Set designer",
        org: "Teatro Pequeno",
        start: "2014",
        end: "2019",
        summary:
          "Designed eleven productions for an amateur company, on budgets measured in plywood sheets.",
        public: true,
      },
    ],
    constellation: {
      now: "Making public services plainer to use, finishing a second EP, and keeping Saturdays for the code club.",
      areas: [
        {
          id: "work",
          name: "Design work",
          soFar: "20k+",
          now: "25-40",
          blurb:
            "Sixteen years designing products and public services, mostly for people who don’t choose to use them: patients, commuters, benefit claimants.",
        },
        {
          id: "learning",
          name: "Learning",
          soFar: "10k-20k",
          now: "1-3",
          blurb:
            "Architecture school, a design certificate, and slowly learning Portuguese. Mostly self-directed now.",
        },
        {
          id: "music",
          name: "Music",
          soFar: "5k-10k",
          now: "3-6",
          blurb:
            "Cello since age nine. Lately: field recordings, a small band, and releases I make at the kitchen table.",
        },
        {
          id: "family-friends",
          name: "Family & friends",
          blurb:
            "A partner, a toddler, a sister in Bergen and a Sunday-dinner table that keeps growing.",
        },
        {
          id: "running",
          name: "Running",
          soFar: "2k-5k",
          now: "1-3",
          blurb: "Early-morning runs along the river. Where a lot of thinking happens.",
        },
        {
          id: "community",
          name: "Community",
          soFar: "500-2k",
          now: "3-6",
          blurb:
            "The Rua Verde garden and Saturday Code Club: two places where the neighbourhood meets.",
        },
        {
          id: "letters-clay",
          name: "Letters & clay",
          soFar: "500-2k",
          now: "1-3",
          blurb: "Drawing a typeface and throwing pots. Slow crafts that forgive mistakes.",
        },
        {
          id: "theatre",
          name: "Theatre",
          soFar: "500-2k",
          now: "none",
          blurb:
            "Youth theatre in Bergen, then years building sets for an amateur company. Resting for now.",
        },
        {
          id: "beekeeping",
          name: "Beekeeping",
          soFar: "lt100",
          now: "1-3",
          blurb: "The newest part of Noor’s life: two hives on the garden roof since May.",
        },
      ],
      assign: {
        t2: "theatre",
      },
      links: [
        {
          id: "n1",
          from: "t1",
          to: "l1",
          rel: "changed_direction",
          note: "Building sets at fifteen is the reason I studied architecture.",
          status: "confirmed",
        },
        {
          id: "n2",
          from: "l1",
          to: "w1",
          rel: "led_to",
          note: "My thesis on station signage got me the interview.",
          status: "confirmed",
        },
        {
          id: "n3",
          from: "m2",
          to: "w5",
          rel: "inspired",
          note: "The tram’s stop sounds started as recordings from my morning walks.",
          status: "confirmed",
        },
        {
          id: "n4",
          from: "r1",
          to: "m4",
          rel: "inspired",
          note: "Most of the EP was written in my head on long runs by the river.",
          status: "confirmed",
        },
        {
          id: "n5",
          from: "l2",
          to: "k2",
          rel: "led_to",
          note: "I came home from Porto and started drawing letters the same week.",
          status: "confirmed",
        },
        {
          id: "n6",
          from: "k3",
          to: "m4",
          rel: "fed_into",
          note: "The first thing I ever printed became the cover.",
          status: "confirmed",
        },
        {
          id: "n7",
          from: "c2",
          to: "w8",
          rel: "developed",
          note: "If a twelve-year-old can’t follow it, neither can a tired adult.",
          status: "confirmed",
        },
        {
          id: "n8",
          from: "p1",
          to: "c1",
          rel: "led_to",
          note: "I joined the garden to meet my neighbours in my first month.",
          status: "confirmed",
        },
        {
          id: "n9",
          from: "c1",
          to: "b1",
          rel: "led_to",
          note: "The garden needed pollinators. I volunteered before I knew what I was doing.",
          status: "confirmed",
        },
        {
          id: "n10",
          from: "c1",
          to: "m6",
          rel: "led_to",
          note: "The director heard Salt Choir play at a garden party.",
          status: "confirmed",
        },
        {
          id: "n11",
          from: "w3",
          to: "l4",
          rel: "led_to",
          note: "Testing with older adults showed me how much I didn’t know.",
          status: "confirmed",
        },
        {
          id: "n12",
          from: "l4",
          to: "c3",
          rel: "shaped",
          note: "The same principles, for eleven-year-olds.",
          status: "confirmed",
        },
        {
          id: "n13",
          from: "w5",
          to: "w9",
          rel: "led_to",
          note: "",
          status: "confirmed",
        },
        {
          id: "n14",
          from: "t2",
          to: "w5",
          rel: "shaped",
          note: "Sets taught me to design for people moving through a space.",
          status: "confirmed",
        },
      ],
      horizon: [
        {
          id: "h1",
          area: "music",
          title: "Release Salt Light",
          when: "Spring 2027",
        },
        {
          id: "h2",
          area: "community",
          title: "Open-source the accessible curriculum",
          when: "2027",
        },
        {
          id: "h3",
          area: "beekeeping",
          title: "First honey harvest",
          when: "Summer 2027",
        },
        {
          id: "h4",
          area: "work",
          title: "Mentor two junior designers",
          when: "Ongoing",
        },
        {
          id: "h5",
          area: "letters-clay",
          title: "Finish the Halvor Grotesk italic",
          when: "Someday soon",
        },
      ],
    },
  },
  entries: [
    {
      id: "w3",
      title: "Medication reminders for older adults",
      category: "Creation",
      date: "2016-03",
      text: "Co-designed a reminder system with 40 people over 75. The pilot halved missed doses, and the testers rewrote half the copy.",
      public: true,
      domain: "Work",
    },
    {
      id: "w5",
      title: "Wayfinding for the Tidewater Line",
      category: "Creation",
      date: "2022-05",
      text: "Signs, sound cues and a paper map for a new tram line. Each stop has its own short sound, built from recordings of that street.",
      public: true,
      domain: "Work",
    },
    {
      id: "w9",
      title: "Inclusive Design Award, Lisbon",
      category: "Milestone",
      date: "2023-09",
      text: "Given to the Tidewater Line team. Noor accepted it with the three blind riders who tested every stop.",
      public: true,
      domain: "Work",
    },
    {
      id: "w6",
      title: "Plain-language benefits service",
      category: "Creation",
      date: "2024-11",
      text: "Rewriting how residents apply for housing support, from a 14-page form to a guided conversation.",
      public: true,
      status: "In progress",
      domain: "Work",
    },
    {
      id: "w7",
      title: "Designing with people, not for them",
      category: "Learning",
      date: "2016-04",
      text: "Co-design: running sessions where the people affected make the key decisions.",
      public: true,
      status: "Evergreen",
      domain: "Work",
    },
    {
      id: "w8",
      title: "Explaining complex systems simply",
      category: "Learning",
      date: "2021-10",
      text: "Turning policy, code or tram timetables into something a tired person can follow.",
      public: true,
      status: "Evergreen",
      domain: "Work",
    },
    {
      id: "l1",
      title: "BA Architecture, Oslo School of Architecture",
      category: "Learning",
      date: "2006-06",
      text: "Four years of models, crits and night buses. Left wanting to design the experience of a building more than the building.",
      public: true,
      domain: "Learning",
    },
    {
      id: "l4",
      title: "Inclusive design certificate",
      category: "Learning",
      date: "2018-02",
      text: "Part-time course on accessibility, disability-led research and plain language.",
      public: true,
      domain: "Learning",
    },
    {
      id: "l2",
      title: "Letterpress weekend, Porto",
      category: "Learning",
      date: "2021-03",
      text: "Two days setting metal type by hand. Came home with inky fingers and a question about why letters look the way they do.",
      public: true,
      domain: "Learning",
    },
    {
      id: "l3",
      title: "Learning Portuguese",
      category: "Creation",
      date: "2019-05",
      text: "From zero at 32. Now confident enough to argue about compost in it.",
      public: true,
      status: "Evergreen",
      domain: "Learning",
    },
    {
      id: "l5",
      title: "Reading group: cities & care",
      category: "Creation",
      date: "2022-09",
      text: "Six friends, one book a month, about how cities look after people or don’t.",
      public: true,
      status: "Evergreen",
      domain: "Learning",
    },
    {
      id: "m1",
      title: "Cello",
      category: "Creation",
      date: "1996-11",
      text: "Started at nine in Bergen. Still practises most mornings, badly and happily.",
      public: true,
      status: "Evergreen",
      domain: "Music",
    },
    {
      id: "m3",
      title: "Salt Choir (band)",
      category: "Creation",
      date: "2020-04",
      text: "A four-piece that formed around the garden’s summer parties: cello, accordion, voice and a borrowed drum machine.",
      public: true,
      status: "Evergreen",
      domain: "Music",
    },
    {
      id: "m2",
      title: "Field-recording walks",
      category: "Creation",
      date: "2019-10",
      text: "Walking the city with a small recorder. Trams, gulls, market calls. The raw material for most of her music now.",
      public: true,
      status: "Evergreen",
      domain: "Music",
    },
    {
      id: "m4",
      title: "Long Rivers (EP)",
      category: "Creation",
      date: "2021-06",
      text: "Five pieces for cello and river recordings, self-released. Written mostly while running.",
      public: true,
      domain: "Music",
    },
    {
      id: "m6",
      title: "Score for “Harbour” (short film)",
      category: "Creation",
      date: "2023-02",
      text: "Twelve minutes of music for a neighbour’s documentary about the last ferry workers.",
      public: true,
      domain: "Music",
    },
    {
      id: "m5",
      title: "Salt Light, second EP (in progress)",
      category: "Creation",
      date: "2025-03",
      text: "Six tracks recorded at home around a toddler’s nap schedule. Four are done.",
      public: true,
      status: "In progress",
      domain: "Music",
    },
    {
      id: "p1",
      title: "Moved to Lisbon",
      category: "Milestone",
      date: "2019-05",
      text: "Left Oslo with two suitcases and a cello case.",
      public: true,
      domain: "Family & friends",
    },
    {
      id: "p3",
      title: "Sunday dinners",
      category: "Creation",
      date: "2021-09",
      text: "A long table on the roof terrace. Whoever turns up, cooks.",
      public: true,
      status: "Evergreen",
      domain: "Family & friends",
    },
    {
      id: "p2",
      title: "Became a parent",
      category: "Milestone",
      date: "2024-11",
      text: "Her son arrived in March 2024. Everything else rearranged itself around him.",
      public: true,
      domain: "Family & friends",
    },
    {
      id: "r1",
      title: "Running before sunrise",
      category: "Creation",
      date: "2019-04",
      text: "Most days, 6 a.m., along the Tagus. Twenty minutes or two hours.",
      public: true,
      status: "Evergreen",
      domain: "Running",
    },
    {
      id: "r2",
      title: "First marathon, Lisbon",
      category: "Milestone",
      date: "2022-10",
      text: "4:21. Walked the last bridge, cried at the finish, signed up for the next one that evening.",
      public: true,
      domain: "Running",
    },
    {
      id: "r3",
      title: "Pacing new runners at parkrun",
      category: "Creation",
      date: "2023-06",
      text: "Runs at the back of the pack on Saturday mornings so nobody finishes alone.",
      public: true,
      status: "Evergreen",
      domain: "Running",
    },
    {
      id: "c1",
      title: "Rua Verde community garden",
      category: "Creation",
      date: "2019-02",
      text: "Joined in her first month in Lisbon; co-organizer since 2021. Forty plots, one shared shed, endless meetings.",
      public: true,
      status: "Evergreen",
      domain: "Community",
    },
    {
      id: "c4",
      title: "The garden’s seed library",
      category: "Creation",
      date: "2023-03",
      text: "A cabinet of labelled seed packets anyone can borrow from and return to at harvest.",
      public: true,
      domain: "Community",
    },
    {
      id: "c2",
      title: "Saturday Code Club",
      category: "Creation",
      date: "2021-05",
      text: "Volunteer teacher for 10–14 year olds at the local library. Games, robots, and a lot of patience.",
      public: true,
      status: "Evergreen",
      domain: "Community",
    },
    {
      id: "c3",
      title: "Accessible Code Club curriculum",
      category: "Creation",
      date: "2024-09",
      text: "Rewriting the club’s lessons so kids who use screen readers or switch controls can take part fully.",
      public: true,
      status: "In progress",
      domain: "Community",
    },
    {
      id: "k3",
      title: "Cover lettering for Long Rivers",
      category: "Creation",
      date: "2021-11",
      text: "Hand-set wood type, printed on the Porto workshop’s proof press, scanned for the EP cover.",
      public: true,
      domain: "Letters & clay",
    },
    {
      id: "k1",
      title: "Wheel-thrown ceramics",
      category: "Creation",
      date: "2022-04",
      text: "A shared studio two streets away. Mostly bowls. Mostly slightly wonky.",
      public: true,
      status: "Evergreen",
      domain: "Letters & clay",
    },
    {
      id: "k2",
      title: "Halvor Grotesk (typeface in progress)",
      category: "Creation",
      date: "2023-10",
      text: "A sans-serif drawn for signs that are read from a moving tram. Regular and bold are done; italic is next.",
      public: true,
      status: "In progress",
      domain: "Letters & clay",
    },
    {
      id: "t1",
      title: "Youth theatre, Bergen",
      category: "Creation",
      date: "2001-06",
      text: "Acting badly, then building sets well. The workshop felt more like home than the stage.",
      public: true,
      domain: "Theatre",
    },
    {
      id: "t3",
      title: "Last show: “The Lighthouse Keepers”",
      category: "Milestone",
      date: "2019-02",
      text: "The final set before moving to Lisbon: a lighthouse that turned on stage.",
      public: true,
      domain: "Theatre",
    },
    {
      id: "b1",
      title: "Beginner beekeeping course",
      category: "Learning",
      date: "2026-03",
      text: "Six Saturdays with the city beekeepers’ association. Stung twice, hooked anyway.",
      public: true,
      domain: "Beekeeping",
    },
    {
      id: "b2",
      title: "Two hives on the garden roof",
      category: "Creation",
      date: "2026-05",
      text: "Installed in May. Named Fado and Fita by the code-club kids.",
      public: true,
      status: "Evergreen",
      domain: "Beekeeping",
    },
  ],
};
